import { McpServer } from "@modelcontextprotocol/sdk/server/mcp";
import { Request } from "express";
import { IMcpTool } from "../IMcpTool";
import { z } from "zod";
import { McpUtilities } from "../mcp-utilities";

// ── GenerateSoapNote (Agent 2) ────────────────────────────────
class GenerateSoapNoteTool implements IMcpTool {
  registerTool(server: McpServer, _req: Request) {
    server.registerTool(
      "GenerateSoapNote",
      {
        description:
          "Generates a structured SOAP-formatted clinical note from pre-visit intake data for physician review. Feed in data from GetPatientMedications, GetPatientAllergies, GetPatientLabResults, and GetPatientVitals.",
        inputSchema: {
          chiefComplaint: z.string().describe("Patient's main reason for the visit in their own words"),
          symptomDescription: z.string().describe("Detailed description including onset, duration, severity, and character"),
          currentMedications: z.array(z.string()).describe("Current medications with dosages"),
          allergies: z.array(z.string()).describe("Known allergies and reaction types"),
          relevantHistory: z.string().describe("Relevant past medical history and conditions from patient FHIR record"),
          recentLabs: z.string().optional().describe("Recent lab results summary from GetPatientLabResults"),
          vitals: z.string().optional().describe("Recent vitals from GetPatientVitals"),
          visitType: z.enum(["new_patient", "follow_up", "chronic_disease", "pre_surgical"]).optional().describe("Type of visit"),
        },
      },
      async ({ chiefComplaint, symptomDescription, currentMedications, allergies, relevantHistory, recentLabs, vitals, visitType }) => {
        const visitLabels: Record<string, string> = {
          new_patient: "New Patient Visit",
          follow_up: "Follow-Up Visit",
          chronic_disease: "Chronic Disease Management",
          pre_surgical: "Pre-Surgical / Procedure Evaluation",
        };
        const visitLabel = visitType ? visitLabels[visitType] : "Outpatient Visit";
        const today = new Date().toISOString().split("T")[0];

        const note = `SOAP NOTE — ${visitLabel}
Generated: ${today}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

SUBJECTIVE
━━━━━━━━━━
Chief Complaint:
  ${chiefComplaint}

History of Present Illness (HPI):
  ${symptomDescription}

Current Medications:
${currentMedications.length > 0 ? currentMedications.map((m) => `  • ${m}`).join("\n") : "  • No medications reported"}

Allergies:
${allergies.length > 0 ? allergies.map((a) => `  • ${a}`).join("\n") : "  • No Known Allergies (NKA)"}

OBJECTIVE
━━━━━━━━━
Vitals:
  ${vitals ?? "Not provided — obtain at visit"}

Recent Laboratory Data:
  ${recentLabs ?? "None available — order as clinically indicated"}

Pertinent Medical History:
  ${relevantHistory}

ASSESSMENT
━━━━━━━━━━
Problem List (to be finalized by physician):
  [ ] ${chiefComplaint}
  [ ] Review chronic conditions for stability
  [ ] Review medication list for changes or interactions
  [ACTION NEEDED] Physician to complete differential assessment at visit

PLAN
━━━━
  [ ] Address chief complaint: ${chiefComplaint}
  [ ] Reconcile and verify current medication list
  [ ] Order or review relevant diagnostic tests
  [ ] Update active problem list
  [ ] Schedule follow-up as appropriate
  [ACTION NEEDED] All plan items to be confirmed by physician at time of visit

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
DISCLAIMER: Generated by AI pre-visit intake system.
All clinical decisions must be made and verified by the treating physician.`;

        return McpUtilities.createTextResponse(JSON.stringify({
          soapNote: note,
          visitType: visitLabel,
          generatedDate: today,
          note: "Items marked [ACTION NEEDED] require physician attention at time of visit.",
        }, null, 2));
      },
    );
  }
}

// ── ReconcileMedications (Agent 3) ────────────────────────────
const MedicationSchema = z.object({
  name: z.string(),
  dose: z.string().optional(),
  frequency: z.string().optional(),
});

class ReconcileMedicationsTool implements IMcpTool {
  registerTool(server: McpServer, _req: Request) {
    server.registerTool(
      "ReconcileMedications",
      {
        description:
          "Compares pre-admission and post-discharge medication lists. Returns NEW, CHANGED, STOPPED, and CONTINUED medications with red flags for high-risk discontinuations. Core tool for the Care Transition Coordinator.",
        inputSchema: {
          preAdmissionMeds: z.array(MedicationSchema).describe("Medications before admission from GetPatientMedications"),
          dischargeMeds: z.array(MedicationSchema).describe("Medications prescribed at discharge"),
        },
      },
      async ({ preAdmissionMeds, dischargeMeds }) => {
        const preNames = preAdmissionMeds.map((m) => m.name.toLowerCase());
        const dischargeNames = dischargeMeds.map((m) => m.name.toLowerCase());

        const newMeds = dischargeMeds.filter((m) => !preNames.includes(m.name.toLowerCase()));
        const stoppedMeds = preAdmissionMeds.filter((m) => !dischargeNames.includes(m.name.toLowerCase()));
        const continuedMeds = dischargeMeds.filter((m) => preNames.includes(m.name.toLowerCase()));
        const changedMeds = continuedMeds.filter((dm) => {
          const pre = preAdmissionMeds.find((p) => p.name.toLowerCase() === dm.name.toLowerCase());
          return pre?.dose && dm.dose && pre.dose !== dm.dose;
        });

        const highRiskTerms = ["warfarin", "coumadin", "insulin", "metformin", "lisinopril", "metoprolol", "amlodipine", "aspirin", "clopidogrel", "plavix", "prednisone", "levothyroxine", "synthroid", "digoxin", "furosemide"];
        const opioidTerms = ["oxycodone", "hydrocodone", "morphine", "tramadol", "fentanyl", "opioid", "codeine"];

        const redFlags: string[] = [];
        const highRiskStops = stoppedMeds.filter((m) => highRiskTerms.some((hr) => m.name.toLowerCase().includes(hr)));
        if (highRiskStops.length > 0) redFlags.push(`HIGH-RISK medications stopped: ${highRiskStops.map((m) => m.name).join(", ")} — verify intentional discontinuation with prescriber.`);

        const newOpioids = newMeds.filter((m) => opioidTerms.some((o) => m.name.toLowerCase().includes(o)));
        if (newOpioids.length > 0) redFlags.push(`New opioid prescribed (${newOpioids.map((m) => m.name).join(", ")}) — confirm patient education on dosing, risks, and drug interactions.`);

        return McpUtilities.createTextResponse(JSON.stringify({
          reconciliationSummary: {
            newMedications: newMeds.map((m) => ({ ...m, counselingNote: "Patient has not taken this before — education required" })),
            changedMedications: changedMeds.map((m) => {
              const pre = preAdmissionMeds.find((p) => p.name.toLowerCase() === m.name.toLowerCase());
              return { name: m.name, previousDose: pre?.dose, newDose: m.dose, frequency: m.frequency };
            }),
            stoppedMedications: stoppedMeds.map((m) => ({ ...m, counselingNote: "Patient must be told explicitly NOT to continue this medication" })),
            continuedMedications: continuedMeds.filter((m) => !changedMeds.find((c) => c.name === m.name)),
          },
          counts: { new: newMeds.length, changed: changedMeds.length, stopped: stoppedMeds.length, continued: continuedMeds.length - changedMeds.length },
          redFlags,
          patientCounselingPoints: [
            newMeds.length > 0 ? `Educate on ${newMeds.length} new medication(s): ${newMeds.map((m) => m.name).join(", ")}` : null,
            stoppedMeds.length > 0 ? `Confirm patient will NOT continue ${stoppedMeds.length} stopped medication(s): ${stoppedMeds.map((m) => m.name).join(", ")}` : null,
            changedMeds.length > 0 ? `Clarify dose changes for ${changedMeds.length} medication(s)` : null,
          ].filter(Boolean),
        }, null, 2));
      },
    );
  }
}

// ── BuildRecoveryTimeline (Agent 3) ───────────────────────────
class BuildRecoveryTimelineTool implements IMcpTool {
  registerTool(server: McpServer, _req: Request) {
    server.registerTool(
      "BuildRecoveryTimeline",
      {
        description:
          "Builds a post-discharge recovery timeline with day-by-day milestone check-ins, activity progression reminders, and appointment prompts. Used by the Care Transition Coordinator to proactively support patient recovery.",
        inputSchema: {
          procedureOrCondition: z.string().describe("What the patient was treated for or discharged with"),
          dischargeDate: z.string().describe("Discharge date in YYYY-MM-DD format"),
          followupDate: z.string().optional().describe("Follow-up appointment date in YYYY-MM-DD format"),
          dischargeMedications: z.array(z.string()).optional().describe("Discharge medication names for refill reminders"),
        },
      },
      async ({ procedureOrCondition, dischargeDate, followupDate, dischargeMedications }) => {
        const discharge = new Date(dischargeDate);
        const addDays = (date: Date, days: number): string => {
          const d = new Date(date);
          d.setDate(d.getDate() + days);
          return d.toISOString().split("T")[0];
        };

        const timeline = [
          {
            day: 0, date: dischargeDate, label: "Discharge Day",
            milestones: ["Pick up ALL prescriptions before going home", "Read discharge instructions carefully", "Set up medication reminders", "Confirm follow-up appointment is scheduled", "Arrange caregiver support for first 24-48 hours"],
            checkInPrompt: "Do you have all your medications and a clear understanding of your instructions?",
          },
          {
            day: 1, date: addDays(discharge, 1), label: "Day 1 — First Day Home",
            milestones: ["Take all scheduled medications on time", "Rest — avoid strenuous activity", "Check wound or incision site if applicable", "Stay hydrated and eat light meals"],
            checkInPrompt: "How are you feeling today? Any pain, fever, or concerns with your medications?",
          },
          {
            day: 3, date: addDays(discharge, 3), label: "Day 3 — Early Recovery Check",
            milestones: ["Pain level should be improving — contact doctor if not", "Review medication adherence", "Begin light activity if cleared (short walks)", "Check wound for signs of infection"],
            checkInPrompt: "Are you managing pain well? Any medication issues or wound concerns?",
          },
          {
            day: 7, date: addDays(discharge, 7), label: "Day 7 — One Week Milestone",
            milestones: [
              "Assess overall recovery progress",
              "Confirm follow-up appointment is on the calendar",
              "Gradually increase activity as tolerated",
              dischargeMedications?.length ? `Check supply of: ${dischargeMedications.join(", ")} — refill if running low` : "Check medication supply and refill if needed",
            ],
            checkInPrompt: "One week out — how is recovery progressing? Any new or worsening symptoms?",
          },
          {
            day: 14, date: addDays(discharge, 14), label: "Day 14 — Two Week Review",
            milestones: ["Most activity restrictions lift for minor procedures — confirm with doctor", "Wound should be well-healed", "Review time-limited medications", "Prepare questions for follow-up appointment"],
            checkInPrompt: "Two weeks post-discharge — are you back to your normal baseline? Any concerns for your follow-up?",
          },
        ];

        if (followupDate) {
          const followup = new Date(followupDate);
          const daysDiff = Math.round((followup.getTime() - discharge.getTime()) / (1000 * 60 * 60 * 24));
          if (![0, 1, 3, 7, 14].includes(daysDiff)) {
            timeline.push({ day: daysDiff, date: followupDate, label: "Follow-Up Appointment", milestones: ["Bring complete medication list", "Bring written list of questions", "Report any new or worsening symptoms", "Ask about return to full normal activity"], checkInPrompt: "Your follow-up appointment is today. Bring your medication list and questions." });
            timeline.sort((a, b) => a.day - b.day);
          }
        }

        return McpUtilities.createTextResponse(JSON.stringify({
          procedureOrCondition,
          dischargeDate,
          followupDate: followupDate ?? "Not yet scheduled",
          totalCheckpoints: timeline.length,
          recoveryTimeline: timeline,
          generalWarnings: [
            "CALL 911: chest pain, difficulty breathing, sudden confusion, uncontrolled bleeding",
            "CALL DOCTOR IMMEDIATELY: fever >101.5°F, severe uncontrolled pain, signs of wound infection",
          ],
        }, null, 2));
      },
    );
  }
}

export const GenerateSoapNoteToolInstance = new GenerateSoapNoteTool();
export const ReconcileMedicationsToolInstance = new ReconcileMedicationsTool();
export const BuildRecoveryTimelineToolInstance = new BuildRecoveryTimelineTool();